---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-ms
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-ms
  template:
    metadata:
      labels:
        app: delivery-ms
    spec:
      containers:
      - name: delivery-ms
        image: mayurikulkarni2024/delivery-ms:latest
        ports:
        - containerPort: 8084
        envFrom:
            - configMapRef:
                name: delivery-ms-config